//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Avatar { get; set; }
        public Nullable<int> Categoryld { get; set; }
        public string ShortDes { get; set; }
        public string FullDescriout { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<double> PriceDiscout { get; set; }
        public Nullable<int> Typeld { get; set; }
        public string Slug { get; set; }
        public Nullable<int> Brandld { get; set; }
        public Nullable<bool> Deleted { get; set; }
        public Nullable<bool> ShowOnHomepage { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<System.DateTime> CreatedOnUct { get; set; }
        public Nullable<System.DateTime> UpdatedOnUct { get; set; }
    }
}
